export const categories = [
  "Inverters",
  "Batteries",
  "Panels",
  "Kits",
  "Accessories",
];

export const brands = ["SolarMart", "Luminous", "BlueGate", "Jinko", "Growatt"];

export const products = [
  {
    id: "sm-3kva-kit",
    slug: "3kva-home-solar-kit",
    name: "3kVA Home Solar Kit",
    category: "Kits",
    brand: "SolarMart",
    sku: "SM-KIT-3KVA",
    price: 1850000,
    rating: 4.8,
    availability: "In stock",
    stock: 9,
    images: [
      "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "A dependable starter kit for homes that need clean backup power.",
    description:
      "This 3kVA kit is designed for apartments and small family homes that need reliable electricity for lights, televisions, routers, fans, and refrigeration. It includes matched components for stable daily use and lower energy costs over time.",
    features: [
      "3kVA hybrid inverter",
      "2 x 5kWh lithium batteries",
      "6 high-efficiency solar panels",
      "Installation accessories included",
    ],
    variants: ["Standard", "Installation Included"],
    relatedIds: ["growatt-5kva-inverter", "jinko-550w-panel", "lithium-5kwh-battery"],
  },
  {
    id: "growatt-5kva-inverter",
    slug: "growatt-5kva-hybrid-inverter",
    name: "Growatt 5kVA Hybrid Inverter",
    category: "Inverters",
    brand: "Growatt",
    sku: "GRW-INV-5KVA",
    price: 920000,
    rating: 4.7,
    availability: "In stock",
    stock: 14,
    images: [
      "https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Efficient inverter for medium energy demand and expandable solar systems.",
    description:
      "A 5kVA hybrid inverter suitable for homes, offices, and growing small businesses that need dependable energy conversion and battery integration.",
    features: [
      "Pure sine wave output",
      "Battery and solar-ready",
      "Smart LCD monitoring",
      "Low-noise operation",
    ],
    variants: ["5kVA"],
    relatedIds: ["lithium-5kwh-battery", "sm-5kva-kit", "jinko-550w-panel"],
  },
  {
    id: "lithium-5kwh-battery",
    slug: "5kwh-lithium-battery",
    name: "5kWh Lithium Battery",
    category: "Batteries",
    brand: "SolarMart",
    sku: "SM-BAT-5KWH",
    price: 1250000,
    rating: 4.9,
    availability: "In stock",
    stock: 18,
    images: [
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Long-life storage battery for homes and business installations.",
    description:
      "A durable lithium battery designed for frequent cycling, fast charge efficiency, and long backup duration in residential and commercial setups.",
    features: [
      "High depth of discharge",
      "Fast recharge support",
      "Wall or rack mount",
      "BMS protection built in",
    ],
    variants: ["5kWh"],
    relatedIds: ["growatt-5kva-inverter", "sm-3kva-kit", "sm-10kva-kit"],
  },
  {
    id: "jinko-550w-panel",
    slug: "jinko-550w-solar-panel",
    name: "Jinko 550W Solar Panel",
    category: "Panels",
    brand: "Jinko",
    sku: "JNK-PNL-550W",
    price: 165000,
    rating: 4.6,
    availability: "In stock",
    stock: 52,
    images: [
      "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "High-output panel for efficient rooftop and ground installations.",
    description:
      "A trusted monocrystalline panel option for customers looking to maximize generation with fewer modules and strong brand reliability.",
    features: [
      "550W output",
      "Weather-resistant frame",
      "High conversion efficiency",
      "Long service life",
    ],
    variants: ["550W"],
    relatedIds: ["sm-3kva-kit", "sm-10kva-kit", "roof-mount-kit"],
  },
  {
    id: "sm-5kva-kit",
    slug: "5kva-family-solar-kit",
    name: "5kVA Family Solar Kit",
    category: "Kits",
    brand: "SolarMart",
    sku: "SM-KIT-5KVA",
    price: 3250000,
    rating: 4.9,
    availability: "In stock",
    stock: 7,
    images: [
      "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "A balanced solar package for family homes and efficient office use.",
    description:
      "This 5kVA system is built for homes and businesses with moderate daily use, supporting refrigeration, office devices, entertainment, and lighting with lower dependence on generator fuel.",
    features: [
      "5kVA hybrid inverter",
      "3 x 5kWh lithium batteries",
      "10 solar panels",
      "Monitoring and installation support",
    ],
    variants: ["Standard", "Premium Installation"],
    relatedIds: ["growatt-5kva-inverter", "lithium-5kwh-battery", "jinko-550w-panel"],
  },
  {
    id: "sm-10kva-kit",
    slug: "10kva-business-solar-kit",
    name: "10kVA Business Solar Kit",
    category: "Kits",
    brand: "SolarMart",
    sku: "SM-KIT-10KVA",
    price: 5950000,
    rating: 5,
    availability: "Limited stock",
    stock: 4,
    images: [
      "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "A larger system for demanding homes, offices, and commercial use.",
    description:
      "Built for heavier loads and stronger uptime requirements, this package supports business continuity and premium residential comfort with lower long-term operating costs.",
    features: [
      "10kVA inverter system",
      "4 x 5kWh lithium batteries",
      "18 solar panels",
      "Professional system design and installation",
    ],
    variants: ["Business", "Enterprise"],
    relatedIds: ["jinko-550w-panel", "lithium-5kwh-battery", "roof-mount-kit"],
  },
  {
    id: "roof-mount-kit",
    slug: "roof-mount-accessory-kit",
    name: "Roof Mount Accessory Kit",
    category: "Accessories",
    brand: "SolarMart",
    sku: "SM-ACC-RMK",
    price: 115000,
    rating: 4.5,
    availability: "In stock",
    stock: 21,
    images: [
      "https://images.unsplash.com/photo-1592833159155-c62df1b65634?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Mounting kit for safe and tidy rooftop solar installation.",
    description:
      "A practical accessory set for secure panel mounting and improved installation quality on residential and business rooftops.",
    features: [
      "Aluminium rails",
      "Clamps and fasteners",
      "Corrosion-resistant finish",
      "Compatible with common panel sizes",
    ],
    variants: ["Standard"],
    relatedIds: ["jinko-550w-panel", "sm-5kva-kit", "sm-10kva-kit"],
  },
];

export const featuredSlugs = [
  "3kva-home-solar-kit",
  "growatt-5kva-hybrid-inverter",
  "5kwh-lithium-battery",
  "10kva-business-solar-kit",
];
